### ISSUE TITLE
Links to notebooks don't work

### ISSUE THREAD

**Issue by mikecroucher** [christianp/jupyter-interactions-site#1]
E.g. http://localhost:8888/notebooks/jupyter-interactions/Divisors%20of%20a%20positive%20integers.ipynb

**Comment by christianp** [comment]
Whoops, I used the wrong config file!

**Comment by christianp** [comment]
... and I forgot which repository I was on when I wrote "fixes #1" in the gh-pages commit message. Fixed now, anyway.
